"""Build a non-destructive Supabase migration from the four supplied JSON exports.
Usage: python3 scripts/import-content.py /path/to/exports
"""
import html
import json
import re
import sys
import uuid
from pathlib import Path
from urllib.parse import urlparse


def slug(value):
    return re.sub(r'-+', '-', re.sub(r'[^a-z0-9\s-]', '', value.lower()).strip().replace(' ', '-'))[:80] or 'post'


def uid(value):
    return str(uuid.uuid5(uuid.NAMESPACE_URL, value))


def sql(value):
    if value is None:
        return 'NULL'
    return "'" + str(value).replace("'", "''") + "'"


def js(value):
    return sql(json.dumps(value, ensure_ascii=False)) + '::jsonb'


def valid_url(value):
    parsed = urlparse(value)
    if parsed.scheme not in ('https', 'http') or not parsed.netloc:
        raise ValueError('Invalid source URL: ' + value)
    return value


def build(directory):
    def read(name):
        return json.loads((directory / (name + '.json')).read_text())
    courses, mocks, grouped, questions = map(read, ['courses', 'mock_tests', 'posts_by_category', 'practice_questions'])
    if questions:
        raise ValueError('Practice export is no longer empty; map its question format before importing.')
    out = ['-- Generated by scripts/import-content.py from the supplied exports.',
           '-- Run after 0001 through 0004. Existing records and admin edits are retained.',
           'begin;', "set local standard_conforming_strings = on;"]
    categories = {slug(name): html.unescape(name) for name in grouped}
    for key, name in categories.items():
        out.append(f'insert into public.categories (id,name,slug) values ({sql(uid("category:" + key))},{sql(name)},{sql(key)}) on conflict do nothing;')
    articles = {}
    for category, entries in grouped.items():
        for item in entries:
            url = valid_url(item['url'])
            record = articles.setdefault(url, {'item': item, 'categories': []})
            if slug(category) not in record['categories']:
                record['categories'].append(slug(category))
    for url, record in articles.items():
        item, cats = record['item'], record['categories']
        title = html.unescape(item['title'])
        text = html.unescape(item.get('content_text', ''))
        # Keep the supplied text verbatim apart from decoding HTML entities.
        blocks = [{'id': uid(url + ':text'), 'type': 'paragraph', 'text': text, 'align': 'left', 'width': 100}] if text else []
        images = list(dict.fromkeys(u for u in item.get('images', []) if '/wp-content/uploads/' in u))
        for image in images:
            valid_url(image)
            blocks.append({'id': uid(url + ':' + image), 'type': 'image', 'src': image, 'alt': '', 'align': 'left', 'width': 100})
        excerpt = re.sub(r'\s+', ' ', text).strip()
        if len(excerpt) > 220:
            excerpt = excerpt[:217].rsplit(' ', 1)[0] + '…'
        # URL paths are preserved; stable IDs avoid duplicates even after admin slug edits.
        post_slug = urlparse(url).path.strip('/') or slug(title)
        category_query = '(select id from public.categories where slug=' + sql(cats[0]) + ')'
        extra_query = 'array(select id from public.categories where slug in (' + ','.join(sql(c) for c in cats[1:]) + '))' if len(cats) > 1 else "'{}'::uuid[]"
        # Export timestamps have no timezone; interpret as the source site's India time.
        date = "(" + sql(item['date']) + "::timestamp at time zone 'Asia/Kolkata')" if item.get('date') else 'now()'
        out.append('insert into public.posts (id,title,slug,excerpt,external_url,cover_image,category_id,additional_category_ids,status,content,created_at) values (' + ','.join([sql(uid(url)), sql(title), sql(post_slug), sql(excerpt), sql(url), sql(images[0] if images else None), category_query, extra_query, "'published'", js(blocks), date]) + ') on conflict do nothing;')
    course_categories = ['frcpath-part-1', 'frcpath-part-2', 'approach-based-course', 'hematopathology']
    course_count = 0
    for item in courses:
        if '/courses/' not in urlparse(item['url']).path:
            continue
        url = valid_url(item['url'])
        category = course_categories[course_count]
        data = {'id': 'import-' + uid(url), 'slug': urlparse(url).path.strip('/').split('/')[-1],
                'title': html.unescape(item['title']), 'category': category,
                'tagline': item.get('description', ''), 'subspecialty': 'Hematopathology' if category == 'hematopathology' else 'Histopathology',
                'examTargets': ['FRCPath'] if category.startswith('frcpath') else [],
                'imageUrl': f'/mock/course-thumb-{course_count + 1}.svg', 'priceCents': 0, 'priceOnRequest': True, 'currency': 'INR',
                'externalUrl': url, 'faculty': {'id': '', 'name': '', 'title': '', 'affiliation': '', 'avatarUrl': ''},
                'lessonCount': 0, 'whoFor': [], 'whatYouGet': [], 'curriculum': [], 'faqs': [], 'sampleQuestions': [], 'testimonials': []}
        catalog(out, 'courses', data, course_count)
        course_count += 1
    mock_categories = ['histo-hemat-mocks', 'neuropathology-mocks', 'frcpath-part1-mock']
    mock_count = 0
    for item in mocks:
        if '/courses/' not in urlparse(item['url']).path:
            continue
        url = valid_url(item['url'])
        category = mock_categories[mock_count]
        title = html.unescape(item['title'])
        cat = {'category': category, 'label': title, 'description': ''}
        catalog(out, 'mock_categories', {'id': category, **cat}, mock_count)
        data = {'id': 'import-' + uid(url), 'title': title, 'shortLabel': title, 'category': category,
                'examPattern': 'Mock Test', 'questionCount': 0, 'imageUrl': '/mock/course-thumb-3.svg', 'externalUrl': url}
        catalog(out, 'mock_tests', data, mock_count)
        mock_count += 1
    out.append('commit;')
    return '\n\n'.join(out) + '\n', {'courses': course_count, 'mock_tests': mock_count, 'posts': len(articles), 'categories': len(categories), 'practice_questions': 0}


def catalog(out, kind, data, position):
    # Never overwrite an existing record, including one already added with this URL/slug.
    out.append('insert into public.catalog_items (kind,id,slug,category,position,data) select ' + ','.join([sql(kind), sql(data['id']), sql(data.get('slug')), sql(data.get('category')), str(position - 100), js(data)]) + ' where not exists (select 1 from public.catalog_items where kind=' + sql(kind) + ' and (id=' + sql(data['id']) + (' or data->>\'externalUrl\'=' + sql(data['externalUrl']) if data.get('externalUrl') else '') + (' or slug=' + sql(data['slug']) if data.get('slug') else '') + ')) on conflict do nothing;')


if __name__ == '__main__':
    output, counts = build(Path(sys.argv[1]))
    destination = Path(__file__).resolve().parents[1] / 'supabase/migrations/0005_import_website_content.sql'
    destination.write_text(output)
    print(json.dumps(counts)); print(destination)
